### ISSUE TITLE
`data/hist_fy21` folder empty

### ISSUE THREAD

**Issue by acxz** [stevesdawg/govstat#14]
Command:
`gunicorn -b localhost:5000 govstat:app`

```bash
[2022-02-20 10:47:40 -0500] [964739] [INFO] Starting gunicorn 20.1.0
[2022-02-20 10:47:40 -0500] [964739] [INFO] Listening at: http://127.0.0.1:5000 (964739)
[2022-02-20 10:47:40 -0500] [964739] [INFO] Using worker: sync
[2022-02-20 10:47:40 -0500] [964743] [INFO] Booting worker with pid: 964743
[2022-02-20 10:47:41 -0500] [964743] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/acxz/vcs/git/github/acxz/govstat/govstat.py", line 1, in <module>
    from app import app
  File "/home/acxz/vcs/git/github/acxz/govstat/app/__init__.py", line 22, in <module>
    from app import routes, models
  File "/home/acxz/vcs/git/github/acxz/govstat/app/routes.py", line 8, in <module>
    import app.Budget as Budget
  File "/home/acxz/vcs/git/github/acxz/govstat/app/Budget.py", line 13, in <module>
    EXCEL_FILES = sorted(os.listdir(EXCEL_DIR))
FileNotFoundError: [Errno 2] No such file or directory: '/home/acxz/vcs/git/github/acxz/us/data/hist_fy21'
[2022-02-20 10:47:41 -0500] [964743] [INFO] Worker exiting (pid: 964743)
[2022-02-20 10:47:42 -0500] [964739] [INFO] Shutting down: Master
[2022-02-20 10:47:42 -0500] [964739] [INFO] Reason: Worker failed to boot.
```

**Comment by sseshan7** [comment]
The budget data pipeline is manual and currently has no automation.
I download files from Office of Management and Budget (OMB), and put them in `congress/data/hist_fy21`.

For now, to clear this error, I will bring that directory into *this* repo, so that the files will be available when someone clones/installs govstat. Users will still need to install `congress` for this webapp to function.

**Comment by acxz** [comment]
Can the congress commands be used to download the `hist_fy21` data?
How do you download them in the first place, some command?

**Comment by sseshan7** [comment]
No I manually downloaded them. Would have to build a scraper to download them automatically.
Also, this data doesn't change that often. New files generated 1x per year or so. For that reason, didn't spend time automating.

Nevertheless, automating looks like it's necessary if others want this data. Instead of pushing new files to the repo.

**Comment by acxz** [comment]
Would this scraper fit into unitedstates/congress's scope?

**Comment by sseshan7** [comment]
I don't think so, because it's technically not congress related, it's coming from another branch (executive, OMB).

It would be nice if there was an overarching package for all 3 branches of federal government. One package covering congress data, budget, cabinet, supreme court, judiciary data, etc.
