### ISSUE TITLE
Error with accessing ordered_dates from db

### ISSUE THREAD

**Issue by acxz** [stevesdawg/govstat#17]
Having some more struggles running this locally, requesting live support.

Command: `gunicorn -b localhost:5000 govstat:app`

Output:
```
[2022-02-22 16:18:08,212] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/acxz/venvs/govstat-venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/acxz/vcs/git/github/stevesdawg/govstat/app/routes.py", line 47, in index
    latest_votes = Votes.return_sql_json_by_date(
  File "/home/acxz/vcs/git/github/stevesdawg/govstat/app/Votes.py", line 232, in return_sql_json_by_date
    senate_max_date = senate_ordered.first()[-1].date()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sseshan7** [comment]
I should probably add this to README but run the loader scripts to load votes, bills, and budget into db:
`python vote_loader.py`
`python bill_loader.py`
`python budget_loader.py`
